phases:
  install:
    commands:
      - echo Installing dependencies...
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo Starting the Flask app with Gunicorn...
      - source venv/bin/activate
      - scripts/start_server.sh

  artifacts:
     files:
        - '**/*'    # Include all files generated in the build
