version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Building the Python app...
      - nohup python app.py &  # Run Flask in the background
      - sleep 5  # Wait for Flask to start
      - echo Flask started in the background

artifacts:
  files:
    - '**/*'    # Include all files generated in the build
